#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6

banner "resetrix.biz employee cards — Netlify + DNS go-live"

# ── Stage 1: preflight build ──────────────────────────────────────────────
stage "Preflight — verify the site builds"
say "The card site must build cleanly before we point a domain at it."
note "Run from the card/ directory: npm install && npm run build && npm test"
step "If you have not yet: run 'npm install && npm run build && npm test' in another terminal."
if ! confirm "Build and tests are green?"; then
  warn "Fix the build first, then re-run this wizard."
  exit 1
fi

# ── Stage 2: Netlify site ─────────────────────────────────────────────────
stage "Netlify — create the site"
say "Create a NEW Netlify site for the card (separate from the main Resetrix site)."
open_url "https://app.netlify.com/start"
step "Choose 'Import an existing project' and connect the Git host that holds this repo."
step "When asked for the base directory, set it to: card"
step "Build command and publish directory come from card/netlify.toml (npm run build / dist)."
note "No repo connected yet? Use Netlify Drop instead: run 'npm run build', then"
note "drag the card/dist folder onto https://app.netlify.com/drop"
ask NETLIFY_SITE_URL "Paste the site's default URL (e.g. https://lucky-name-123.netlify.app):"
write_env NETLIFY_SITE_URL "$NETLIFY_SITE_URL"

# ── Stage 3: subdomain ────────────────────────────────────────────────────
stage "Netlify — attach the employee subdomain"
say "Netlify does NOT accept a wildcard '*.resetrix.biz', so attach each employee's"
say "subdomain individually (vernonkoh now, mary next, ...). Each gets its own cert."
step "In Netlify: Site configuration → Domain management → 'Add a domain'."
step "Enter: vernonkoh.resetrix.biz and confirm it under resetrix.biz."
step "Netlify will show which DNS record it expects — keep that page open."
pause "Press Enter once Netlify shows the expected DNS record"

# ── Stage 4: DNS ──────────────────────────────────────────────────────────
stage "DNS — wildcard CNAME"
say "Add a wildcard CNAME at the provider hosting resetrix.biz so future employees"
say "resolve with NO further DNS changes. Point it at the Netlify assignable URL:"
step "Create a CNAME record: name 'subdomain' (e.g. any) → value '$NETLIFY_SITE_URL'."
note "Your DNS provider may not allow '*' for the name — use your provider's wildcard"
note "syntax (often '*' or '@' + an empty/add record) for *.resetrix.biz."
note "If your DNS is Netlify DNS for resetrix.biz, add the wildcard record there."
step "Save it. Propagation usually takes minutes, up to 24h."
pause "Press Enter once the DNS record is saved"

# ── Stage 5: HTTPS ────────────────────────────────────────────────────────
stage "HTTPS — verify the certificate"
say "Netlify provisions a Let's Encrypt certificate once DNS resolves."
step "In Netlify: Site configuration → Domain management → HTTPS → 'Verify DNS configuration'."
step "Wait until the certificate shows as active for vernonkoh.resetrix.biz."
open_url "https://vernonkoh.resetrix.biz"
if ! confirm "Does https://vernonkoh.resetrix.biz load the card with a valid lock icon?"; then
  warn "HTTPS not ready — wait for DNS/cert, then re-run this wizard (it remembers values)."
  exit 1
fi

# ── Stage 6: short link + smoke test ─────────────────────────────────────
stage "Short link + smoke test"
say "Create the Short.io short link that the QR code prints, then smoke test on a phone."
step "In Short.io, create the short link resetrix.biz/vernonkoh → https://vernonkoh.resetrix.biz."
step "Open https://vernonkoh.resetrix.biz on a phone — logo, name, title, company, slogan render."
step "Tap 'Save contact' — a vCard downloads with name, phone, email, website, address, slogan."
step "Tap Call / Email / Website — phone dialer, mail app, and resetrix.com open."
step "Tap Maps — Apple Maps opens on iPhone, Google Maps on Android, at the Paya Lebar Square address."
step "Toggle EN / 中文 — UI and card text switch; reload and confirm the choice is remembered."
step "Scan the printed QR artwork (public/qr/) — it must land on https://resetrix.biz/vernonkoh."
pause "Press Enter when every check passes"

finish
