#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
APP_ENV="$REPO_ROOT/app/.env"
API_ENV="$REPO_ROOT/api/.env"

# Match existing quoted KEY="value" style in app/.env and api/.env.
write_quoted_env() {
	local key="$1" value="$2"
	value="${value%\"}"
	value="${value#\"}"
	write_env "$key" "\"${value}\""
}

TOTAL_STAGES=8

banner "Resetrix Auth0 local setup"

# ── Stage 1 ───────────────────────────────────────────────────────────────
stage "SPA Application"
say "Create or open the Auth0 Single Page Application for Resetrix."
say "Full checklist: docs/auth0-operator-setup.md"
open_url "https://manage.auth0.com/"
step "Applications → Create Application → Single Page Web Application (or open the existing one)."
step "Settings → Allowed Callback URLs: http://localhost:5173/callback"
step "Settings → Allowed Logout URLs: http://localhost:5173"
step "Settings → Allowed Web Origins: http://localhost:5173"
step "Advanced Settings → Grant Types: Authorization Code + Refresh Token"
step "Refresh Tokens: enable Rotation; Absolute + Inactivity Lifetime = 604800 (7 days)"
pause "Press Enter when the SPA Application settings are saved."
ENV_FILE="$APP_ENV"
ask VITE_AUTH0_DOMAIN "Paste the Auth0 domain (bare, e.g. your-tenant.us.auth0.com):"
ask VITE_AUTH0_CLIENT_ID "Paste the SPA Client ID:"

# ── Stage 2 ───────────────────────────────────────────────────────────────
stage "API audience with RBAC"
say "Create (or open) the Auth0 API the SPA and Express API share."
open_url "https://manage.auth0.com/#/apis"
step "Create API (or open existing). Identifier example: https://api.resetrix.dev"
step "RBAC Settings → Enable RBAC + Add Permissions in the Access Token"
step "Permissions tab → add read:profile"
pause "Press Enter when the API and permission exist."
ENV_FILE="$APP_ENV"
ask VITE_AUTH0_AUDIENCE "Paste the API Identifier (audience):"

# ── Stage 3 ───────────────────────────────────────────────────────────────
stage "Role user + read:profile"
open_url "https://manage.auth0.com/#/roles"
step "Create Role named user (if missing)."
step "Assign permission read:profile from the Resetrix API to that role."
pause "Press Enter when the role has read:profile."

# ── Stage 4 ───────────────────────────────────────────────────────────────
stage "Invite-only signup"
open_url "https://manage.auth0.com/#/connections/database"
step "Open your Database connection → disable Sign Ups (ADR-0004)."
pause "Press Enter when public signup is disabled."

# ── Stage 5 ───────────────────────────────────────────────────────────────
stage "Invite a test User"
open_url "https://manage.auth0.com/#/users"
step "Users → Create User (Auth0 sends the default password / verify email)."
step "Assign the user role to that User."
step "Open the verification email and confirm the address (login is denied until verified)."
pause "Press Enter when the User is verified and has the user role."

# ── Stage 6 ───────────────────────────────────────────────────────────────
stage "Post-Login Action (verified email + claims)"
say "Auth0 must deny unverified emails and put profile claims on the access token."
say "Full Action source: docs/auth0-operator-setup.md §5"
open_url "https://manage.auth0.com/#/actions/flows"
step "Actions → Login flow → add/update a Post-Login Action that:"
step "  - api.access.deny(...) when !event.user.email_verified"
step "  - sets namespaced email_verified, roles, email, name on the access token"
pause "Press Enter when the Action is deployed and attached to the Login flow."

# ── Stage 7 ───────────────────────────────────────────────────────────────
stage "Write app/.env"
ENV_FILE="$APP_ENV"
say "Writing SPA Auth0 values to $APP_ENV"
write_quoted_env VITE_AUTH0_DOMAIN "$VITE_AUTH0_DOMAIN"
write_quoted_env VITE_AUTH0_CLIENT_ID "$VITE_AUTH0_CLIENT_ID"
write_quoted_env VITE_AUTH0_AUDIENCE "$VITE_AUTH0_AUDIENCE"

# ── Stage 8 ───────────────────────────────────────────────────────────────
stage "Write api/.env"
ENV_FILE="$API_ENV"
# Strip accidental quotes before composing URLs.
_domain="${VITE_AUTH0_DOMAIN%\"}"
_domain="${_domain#\"}"
_audience="${VITE_AUTH0_AUDIENCE%\"}"
_audience="${_audience#\"}"
AUTH0_ISSUER="https://${_domain}/"
AUTH0_JWKS_URI="https://${_domain}/.well-known/jwks.json"
say "Deriving issuer/JWKS from the SPA domain and writing $API_ENV"
write_quoted_env AUTH0_ISSUER "$AUTH0_ISSUER"
write_quoted_env AUTH0_JWKS_URI "$AUTH0_JWKS_URI"
write_quoted_env AUTH0_AUDIENCE "$_audience"
note "Leave AUTH0_TEST_JWT_SECRET empty for live-tenant runs (tests use it in CI)."

# ──────────────────────────────────────────────────────────────────────────

finish

printf '%sNext — smoke test%s\n' "$BOLD" "$RESET"
say "1. In api/: npm run dev"
say "2. In app/: pnpm dev"
say "3. Open http://localhost:5173/ → Log in → /home Profile → refresh → Log out → /"
say "See docs/auth0-operator-setup.md §6 for the full checklist."
printf '\n'
